name: freebrowse-jupyter
channels:
  - conda-forge
dependencies:
  - python=3.11
  - jupyter_server>=2.0.0,<3
  - nodejs>=20
  - jupyterlab>=4.0.0,<5
  - notebook>=7.0.0,<8
  - nodejs
  - pip
  - pip:
    - -e .
    - ipyniivue
